//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_Code_2021.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_Code_2021.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 137
        ///138
        ///139
        ///140
        ///143
        ///146
        ///147
        ///149
        ///155
        ///156
        ///159
        ///153
        ///163
        ///169
        ///175
        ///180
        ///183
        ///184
        ///206
        ///219
        ///226
        ///233
        ///231
        ///232
        ///234
        ///231
        ///234
        ///231
        ///234
        ///232
        ///230
        ///235
        ///225
        ///237
        ///245
        ///254
        ///263
        ///275
        ///288
        ///290
        ///291
        ///292
        ///316
        ///334
        ///343
        ///346
        ///359
        ///354
        ///352
        ///374
        ///377
        ///378
        ///391
        ///409
        ///419
        ///427
        ///433
        ///437
        ///411
        ///416
        ///435
        ///442
        ///438
        ///440
        ///443
        ///459
        ///460
        ///466
        ///467
        ///468
        ///467
        ///470
        ///488
        ///493
        ///504
        ///505
        ///506
        ///517
        ///523
        ///526
        ///525
        ///532
        ///541
        ///558
        ///559
        ///561
        ///563
        ///565
        ///582
        ///589
        ///595
        ///586
        ///571
        ///603
        ///607
        ///621
        ///634
        ///642
        ///646
        ///648
        ///651
        ///685
        ///70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay1 {
            get {
                return ResourceManager.GetString("DataDay1", resourceCulture);
            }
        }
    }
}
