//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_Code_2021.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_Code_2021.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 137
        ///138
        ///139
        ///140
        ///143
        ///146
        ///147
        ///149
        ///155
        ///156
        ///159
        ///153
        ///163
        ///169
        ///175
        ///180
        ///183
        ///184
        ///206
        ///219
        ///226
        ///233
        ///231
        ///232
        ///234
        ///231
        ///234
        ///231
        ///234
        ///232
        ///230
        ///235
        ///225
        ///237
        ///245
        ///254
        ///263
        ///275
        ///288
        ///290
        ///291
        ///292
        ///316
        ///334
        ///343
        ///346
        ///359
        ///354
        ///352
        ///374
        ///377
        ///378
        ///391
        ///409
        ///419
        ///427
        ///433
        ///437
        ///411
        ///416
        ///435
        ///442
        ///438
        ///440
        ///443
        ///459
        ///460
        ///466
        ///467
        ///468
        ///467
        ///470
        ///488
        ///493
        ///504
        ///505
        ///506
        ///517
        ///523
        ///526
        ///525
        ///532
        ///541
        ///558
        ///559
        ///561
        ///563
        ///565
        ///582
        ///589
        ///595
        ///586
        ///571
        ///603
        ///607
        ///621
        ///634
        ///642
        ///646
        ///648
        ///651
        ///685
        ///70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay1 {
            get {
                return ResourceManager.GetString("DataDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 3
        ///down 4
        ///forward 3
        ///up 4
        ///down 4
        ///down 6
        ///down 3
        ///down 1
        ///up 7
        ///down 7
        ///forward 4
        ///forward 7
        ///forward 3
        ///down 2
        ///forward 5
        ///down 7
        ///forward 5
        ///up 9
        ///down 6
        ///forward 8
        ///forward 8
        ///down 8
        ///forward 7
        ///down 9
        ///down 4
        ///down 6
        ///forward 1
        ///down 2
        ///down 7
        ///up 4
        ///forward 8
        ///down 5
        ///down 7
        ///down 1
        ///forward 5
        ///down 1
        ///up 1
        ///forward 5
        ///forward 1
        ///down 1
        ///forward 3
        ///up 4
        ///up 4
        ///up 8
        ///up 1
        ///forward 7
        ///down 3
        ///forward 3
        ///forward 3
        ///down 3
        ///down 6
        ///down 7
        ///forward 4
        ///down 2
        ///up 3
        ///forward 5
        ///forward 1
        ///down 3
        ///up [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay2 {
            get {
                return ResourceManager.GetString("DataDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010011001001
        ///110101011110
        ///111111000101
        ///100111111001
        ///000000011111
        ///111100100111
        ///011111100000
        ///001001011100
        ///101100111011
        ///010001010100
        ///111011001010
        ///010001100011
        ///110110011011
        ///011011000001
        ///001100101100
        ///001000101100
        ///100000001010
        ///001111110000
        ///100101000000
        ///010000100000
        ///010100110000
        ///110000111101
        ///000001011010
        ///000011011001
        ///011000101110
        ///100011100101
        ///110010010100
        ///001110110101
        ///100011000000
        ///110100111100
        ///100100001111
        ///010110011001
        ///000001111101
        ///100001000010
        ///110010101110
        ///000101001100
        ///10010001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay3 {
            get {
                return ResourceManager.GetString("DataDay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4,75,74,31,76,79,27,19,69,46,98,59,83,23,90,52,87,6,11,92,80,51,43,5,94,17,15,67,25,30,48,47,62,71,85,58,60,1,72,99,3,35,42,10,96,49,37,36,8,44,70,40,45,39,0,63,2,78,68,53,50,77,20,55,38,86,54,93,26,88,12,91,95,34,9,14,33,66,41,13,28,57,29,73,56,22,89,21,64,61,32,65,97,84,18,82,81,7,16,24
        ///
        ///30 46 94 20  2
        ///53 67 69 75 65
        ///27 24 85 28 60
        ///57 58 42 36 78
        ///35 98 87 91 93
        ///
        ///72 71 91 73 19
        /// 2 13 14  8 74
        ///42 34 31 56  9
        ///82 59 44 67 79
        ///49  6 98 10 30
        ///
        ///95 24 25 11 34
        ///57 65 41 92  8
        ///91 26  1 62 38
        ///47 93   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay4 {
            get {
                return ResourceManager.GetString("DataDay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 348,742 -&gt; 620,742
        ///494,864 -&gt; 494,484
        ///193,136 -&gt; 301,136
        ///342,692 -&gt; 342,538
        ///234,525 -&gt; 102,393
        ///72,964 -&gt; 847,189
        ///639,430 -&gt; 99,970
        ///398,791 -&gt; 398,187
        ///181,144 -&gt; 205,168
        ///607,617 -&gt; 416,617
        ///98,339 -&gt; 98,437
        ///763,119 -&gt; 176,119
        ///450,848 -&gt; 450,664
        ///293,133 -&gt; 293,98
        ///308,98 -&gt; 308,15
        ///157,21 -&gt; 405,269
        ///792,471 -&gt; 409,471
        ///42,955 -&gt; 956,41
        ///895,269 -&gt; 895,884
        ///629,635 -&gt; 392,635
        ///169,23 -&gt; 273,127
        ///250,847 -&gt; 250,665
        ///709,56 -&gt; 709,626
        ///938,599 -&gt; 669,868
        ///913,46 -&gt; 458,501
        ///844,417 -&gt; 844,424
        ///178,6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay5 {
            get {
                return ResourceManager.GetString("DataDay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,3,4,1,1,1,1,1,1,1,1,2,2,1,4,2,4,1,1,1,1,1,5,4,1,1,2,1,1,1,1,4,1,1,1,4,4,1,1,1,1,1,1,1,2,4,1,3,1,1,2,1,2,1,1,4,1,1,1,4,3,1,3,1,5,1,1,3,4,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,5,2,5,5,3,2,1,5,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,5,1,1,1,1,5,1,1,1,1,1,4,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,3,1,2,4,1,5,5,1,1,5,3,4,4,4,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,5,3,1,4,1,1,2,2,1,2,2,5,1,1,1,2,1,1,1,1,3,4,5,1,2,1,1,1,1,1,5,2,1,1,1,1,1,1,5,1,1,1,1,1,1,1,5,1,4,1,5,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,5,4,5,1,1,1,1,1,1,1,5,1,1,3,1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay6 {
            get {
                return ResourceManager.GetString("DataDay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,494,43,989,562,667,505,3,630,175,9,1115,348,1135,186,676,122,776,19,1303,9,263,199,628,352,951,31,589,535,975,1153,331,1253,528,1408,972,660,6,3,130,1057,1061,368,535,198,3,472,341,212,560,231,1384,79,265,99,1748,88,741,129,882,173,51,289,987,12,18,318,167,998,1165,255,113,29,279,608,32,395 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay7 {
            get {
                return ResourceManager.GetString("DataDay7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdgcea dgefa efabdg fdgcba dab baefc begd ebdfa db bafgdce | gfbcda cgfadb badcefg eacfgd
        ///eagfdb bafdec fdg edgca gf cdbafeg egfcdb bgaf aedfg defba | gfd edagcbf cdfebg gfedab
        ///faecdgb edgf decag cgf agdcbf aefcb gf dgebca fdaceg cefga | fcg fcbae fg aecgd
        ///abcgdfe gebfd eacbdf gc gbc cabdfg dcfab gdcfb gacd acfegb | fabdc cg bdfeg gbc
        ///bgcda cagdf geafdc fbcdge fedag fc egcabdf gfc gfedba acfe | cdegaf dbfgea adefbg afedcbg
        ///degfbc cdeg dcfbae debfc gbadecf begfca egb eg dbfge adgfb | egfdbc ecgfbd dbcag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay8 {
            get {
                return ResourceManager.GetString("DataDay8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1012349767989212989898755567989899469867895798763210134789998765323234567898999876899994334996876898
        ///2343498754979939876789643459876678998656679987654341945679989994210123499987898965678989129885565797
        ///3456987643467898765698912399765569997543578999965459896789876789422236988976997654555678998764303556
        ///4568998892348999654987929976543457976432347899876598789999865689934545976865889543434589999654212347
        ///5679999989459998799876898765432546987643456964988798679878454567898659895434678932123459899769323467
        ///87 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDay9 {
            get {
                return ResourceManager.GetString("DataDay9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,9 -&gt; 5,9
        ///8,0 -&gt; 0,8
        ///9,4 -&gt; 3,4
        ///2,2 -&gt; 2,1
        ///7,0 -&gt; 7,4
        ///6,4 -&gt; 2,0
        ///0,9 -&gt; 2,9
        ///3,4 -&gt; 1,4
        ///0,0 -&gt; 8,8
        ///5,5 -&gt; 8,2.
        /// </summary>
        internal static string SampleDataDay5 {
            get {
                return ResourceManager.GetString("SampleDataDay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2199943210
        ///3987894921
        ///9856789892
        ///8767896789
        ///9899965678.
        /// </summary>
        internal static string SampleDataDay9 {
            get {
                return ResourceManager.GetString("SampleDataDay9", resourceCulture);
            }
        }
    }
}
